stages:
  - build

build_binary:
  stage: build
  image: golang:buster
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - go get
    - go build -o goverwatch_$CI_COMMIT_TAG.exe main.go
#  only:
#    - master