stages:
  - build

build_binary_with_release_tag:
  stage: build
  image: golang:buster
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apt update && apt upgrade -y
    - apt install libpcap-dev curl -y
    - go get
  script:
    - env GOOS=windows GOARCH=amd64 go build -o goverwatch_$CI_COMMIT_TAG.exe main.go
    - curl --location --request POST 'https://cdn.aptinstall.de/upload' --form 'file=@goverwatch_$CI_COMMIT_TAG.exe' --form 'key=$API_KEY'


build_binary_without_release_tag:
  stage: build
  image: golang:buster
  before_script:
    - apt update && apt upgrade -y
    - apt install libpcap-dev curl gcc-mingw-w64-x86-64 file -y
    - go get
    - export GOOS=windows
    - export GOARCH=amd64
  script:
    - go build -o goverwatch_latest.exe main.go
    - curl --location --request GET 'https://cdn.aptinstall.de/delete?key='$API_KEY'&filename=goverwatch_latest.exe'
    - curl --location --request POST 'https://cdn.aptinstall.de/upload' --form 'file=@goverwatch_latest.exe' --form 'key='$API_KEY
    - file goverwatch_latest.exe
#  only:
#    - master