stages:
  - build

build_binary:
  stage: build
  image: golang:buster
#  rules:
#    - if: $CI_COMMIT_TAG
  before_script:
    - apt update && apt upgrade -y
    - apt install libpcap-dev -y
    - go get
  script:
    - go build -o goverwatch_$CI_COMMIT_TAG.exe main.go
    - ls -al
#  only:
#    - master